MODEL (
  name sqlmesh_dwd.erp_gresa_sa_doc,
  kind INCREMENTAL_BY_TIME_RANGE (
    time_column dw_updatetime,
    lookback 60
  ),
  dialect doris,
  partitioned_by credate,
  physical_properties (
    unique_key = (rsaid, dw_updatetime),
    distributed_by = (kind='HASH', expressions=rsaid, buckets=10),
    replication_allocation = 'tag.location.default: 3',
    in_memory = 'false',
    storage_format = 'V2',
    disable_auto_compaction = 'false'
  ),
  description "零售销售单据"
);

SELECT
  a.rsaid,
  a.dw_updatetime,
  a.is_active,
  a.credate,
  a.useday,
  a.placepointid,
  a.cashierid,
  emp.opcode AS cashieropcode,
  emp.employeename AS cashiername,
  a.insiderid,
  insider.insidercardno,
  insider.insidername,
  a.cncardid,
  a.receivalmoney,
  a.realmoney,
  a.changemoney,
  a.dtl_lines,
  a.handinid,
  a.handinflag,
  a.prescribeid,
  a.bagnum,
  a.usestatus,
  a.manualrate,
  a.manualmoney,
  a.manualpremoney,
  a.marketrate,
  a.marketmoney,
  a.marketpremoney,
  a.rsatype,
  a.dtlmanualmoney,
  a.dtlreducedmoney,
  a.dtlmanualpremoney,
  a.dtlmarketmoney,
  a.dtlmarketpremoney,
  a.combpremoney,
  a.thisintegral,
  a.recstflag,
  a.rsaclass,
  a.invno,
  a.invdate,
  a.invmanid,
  invemp.employeename AS invman,
  pp.placepointname,
  insider.inscardtypeid,
  cardtype.cardtypename,
  a.printflag,
  a.printmanid,
  a.printdate,
  a.djlsh0,
  a.id0000,
  a.grzfe0,
  a.jjzfe0,
  a.gwybz0,
  a.bcbxf0,
  a.grzhye,
  a.zhzfe0,
  a.ylzfje,
  a.cfdxje,
  a.gyzhye,
  a.jkzhzf,
  a.jkzhye,
  a.cfxms0,
  a.gjzhzf,
  a.medflag,
  a.ypxszc,
  a.personname,
  a.personcardid,
  a.memo,
  a.prescriptionid,
  a.scdd,
  a.mallorderno,
  pp.entryid,
  a.regmanname,
  a.customername,
  a.markiman,
  a.departuredate,
  a.arrivaldate,
  IFNULL(pp.taxregisternum, filiale.taxregisternum) AS taxregisternum,
  filiale.kpcode,
  pp.address,
  insider.openid,
  a.zx_ps_phone,
  a.zx_ps_address,
  a.zx_psusestatus,
  a.zx_ps_ks,
  a.signtime,
  a.signflag,
  CASE WHEN a.signflag = 1 THEN '已签收' ELSE '未签收' END AS signstate,
  pszt.ddlname AS pszt,
  a.zx_tcpsxqsj,
  a.zx_psfs
FROM ods_erp.gresa_sa_doc a
LEFT JOIN sqlmesh_dim.erp_pub_employee emp ON a.cashierid = emp.employeeid AND emp.valid_to = DATE('9999-12-31')
LEFT JOIN sqlmesh_dim.erp_gpcs_insider insider ON a.insiderid = insider.insiderid AND insider.valid_to = DATE('9999-12-31')
LEFT JOIN sqlmesh_dim.erp_gpcs_insider_cardtype cardtype ON insider.inscardtypeid = cardtype.inscardtypeid AND cardtype.valid_to = DATE('9999-12-31')
LEFT JOIN sqlmesh_dim.erp_gpcs_placepoint pp ON a.placepointid = pp.placepointid AND pp.valid_to = DATE('9999-12-31')
LEFT JOIN sqlmesh_dim.erp_pub_employee invemp ON a.invmanid = invemp.employeeid AND invemp.valid_to = DATE('9999-12-31')
LEFT JOIN sqlmesh_dim.erp_zx_filiale_info_set filiale ON pp.entryid = filiale.entryid AND filiale.valid_to = DATE('9999-12-31')
LEFT JOIN (SELECT ddlid, ddlname FROM sqlmesh_dim.erp_pub_ddl_dtl WHERE sysid = 102806 AND valid_to = DATE('9999-12-31')) pszt ON IFNULL(a.zx_psusestatus, 0) = pszt.ddlid
WHERE dw_updatetime BETWEEN @start_ds AND @end_ds; 