MODEL (
  name sqlmesh_dim.erp_pub_goods,
  kind FULL,
  dialect doris,
  grain goodsid,
  physical_properties (
    unique_key = (valid_from, valid_to, goodsid),
    distributed_by = (kind='HASH', expressions=goodsid, buckets=1),
    replication_allocation = 'tag.location.default: 3',
    in_memory = 'false',
    storage_format = 'V2',
    disable_auto_compaction = 'false'
  ),
  description "商品维度表",
  column_descriptions (
    goodsid = "商品ID",
    opcode = "操作码",
    goodspinyin = "商品拼音",
    goodsname = "商品名称",
    currencyname = "币种名称",
    goodsengname = "商品英文名",
    goodsinvname = "商品库存名称",
    goodsshortname = "商品简称",
    goodsformalname = "商品正式名称",
    goodsformalpy = "商品正式名称拼音",
    goodsno = "商品编号",
    standardno = "标准编号",
    barcode = "条形码",
    goodstype = "商品类型",
    goodsunit = "商品单位",
    firstapprovedocno = "首次批准文号",
    approvedocno = "批准文号",
    registdocno = "注册证号",
    standardtype = "标准类型",
    factoryid = "厂家ID",
    factoryopcode = "厂家操作码",
    factoryname = "厂家名称",
    validperiod = "有效期",
    respperiod = "响应期",
    periodunit = "期间单位",
    trademark = "商标",
    prodarea = "产地",
    supplytaxrate = "供应税率",
    salestaxrate = "销售税率",
    fixpricetype = "固定价格类型",
    varietyid = "品种ID",
    varietyopcode = "品种操作码",
    varietyname = "品种名称",
    varietydescid = "品种描述ID",
    varietydescopcode = "品种描述操作码",
    varietydescno = "品种描述编号",
    varietydescname = "品种描述名称",
    accflag = "会计标志",
    defaultagtflag = "默认代理标志",
    storagecondition = "储存条件",
    transcondition = "运输条件",
    combinflag = "组合标志",
    customstax = "海关税",
    minreqgoodsqty = "最小需求商品数量",
    financeno = "财务编号",
    otcflag = "OTC标志",
    gmpflag = "GMP标志",
    patentflag = "专利标志",
    securityflag = "安全标志",
    chineseflag = "中文标志",
    medicinetype = "药品类型",
    medicinetypename = "药品类型名称",
    importflag = "进口标志",
    drugflag = "药品标志",
    poisonflag = "毒药标志",
    biomedflag = "生物医学标志",
    bacterinflag = "疫苗标志",
    commonflag = "通用标志",
    medicineflag = "药品标志",
    credate = "创建日期",
    inputmanid = "录入人ID",
    memo = "备注",
    usestatus = "使用状态",
    varietyno = "品种编号",
    busiscope = "经营范围",
    busiscopename = "经营范围名称",
    boxflag = "箱标志",
    integernx = "整数NX",
    function = "功能",
    familyplanflag = "计划生育标志",
    againchkflag = "再次检查标志",
    vardesclassname = "品种描述分类名称",
    vardesclassid = "品种描述分类ID",
    keyconserveflag = "重点保护标志",
    medicinesort = "药品分类",
    toinvdayswarn = "到货天数警告",
    limitedsaleflag = "限售标志",
    leastsaleqty = "最小销售数量",
    ephedrine = "含麻黄碱标志",
    iseggpeptide = "是否蛋肽类制剂标志",
    gspflag = "GSP管控标识",
    ecodeflag = "电子监管码采集标志",
    constituent = "组成成分",
    reqprintquflag = "打印质检单标志",
    highcostflag = "高耗材标志",
    lowcostflag = "低耗材标志",
    importsplitflag = "进口分装标志",
    armariumflag = "医疗设备标志",
    implantable = "植入性器械",
    externalagentia = "体外诊断试剂标志",
    artificialorganflag = "人工器官标志",
    interventional = "介入性器械标志",
    gmpinvaliddate = "GMP证书有效期至",
    productapproval = "产品批件有效期至",
    zx_finance_class = "财务分类",
    querycode = "查询码",
    hiddenflag = "折扣商品标志",
    groupmanagetype = "集团货品管理分类",
    grade = "等级",
    fzskcode = "福州货品税控分类编码",
    materialcode = "物料编码",
    qxfirclass = "器械货品一级分类",
    qxsecclass = "器械货品二级分类",
    busi_zx_finance_class = "经营范围对应财务分类",
    lbfl = "年报分类",
    busi_zx_finance_classname = "经营范围对应财务分类名称",
    lbflname = "年报分类名称",
    zx_finance_class_name = "财务分类名称",
    zx_cytj = "储运条件",
    brandintegration = "厂牌整合",
    groupmanagetypename = "集团货品管理分类名称",
    product_invaliddate = "产品有效期",
    invaliddateflag = "有效期标志",
    skcode = "税控编码",
    splx = "商品类型",
    storageconditionname = "储存条件名称",
    qxbusiclass = "器械业务分类",
    xgflag = "新冠标志",
    dropingflag = "滴剂标志",
    udicode = "UDI编码",
    brandtype = "器械品牌分类",
    relaname = "货品关联名称",
    zx_specgoods_flag = "含特殊复方制剂标志",
    zx_tracecode_prefix = "追溯特征码",
    zx_ssbq = "搜索标签",
    zx_gjypbwm = "国家药品本位码",
    ruleid = "解码规则ID",
    zx_maingoodsid = "主商品ID",
    zx_retainqty = "中药装量",
    zx_zyypgg = "中药规格",
    zx_mainflag = "主标志",
    zx_policyno = "医保编码"
  )
);

WITH ranked_data AS (
    SELECT GOODSID, DW_CREATETIME,
    ROW_NUMBER() OVER (
        PARTITION BY GOODSID
        ORDER BY
            DW_CREATETIME
      ) AS record_seq,
      LEAD (date (DW_CREATETIME), 1, NULL) OVER (
                PARTITION BY
                    GOODSID
                ORDER BY
                    DW_CREATETIME
            ) AS next_start_time
    FROM
      ods_erp.pub_goods
)
SELECT 
CASE
  WHEN a.record_seq = 1 
  THEN DATE('1970-01-01')
  ELSE date(b.DW_CREATETIME)
END AS valid_from,
CASE
  WHEN a.next_start_time IS NOT NULL THEN a.next_start_time
  ELSE DATE('9999-12-31')
END AS valid_to,
  b.goodsid,
  b.opcode,
  b.goodspinyin,
  b.goodsname,
  b.currencyname,
  b.goodsengname,
  b.goodsinvname,
  b.goodsshortname,
  b.goodsformalname,
  b.goodsformalpy,
  b.goodsno,
  b.standardno,
  b.barcode,
  b.goodstype,
  b.goodsunit,
  b.firstapprovedocno,
  b.approvedocno,
  b.registdocno,
  b.standardtype,
  b.factoryid,
  f.factoryopcode,
  f.factoryname,
  b.validperiod,
  b.respperiod,
  b.periodunit,
  b.trademark,
  b.prodarea,
  b.supplytaxrate,
  b.salestaxrate,
  b.fixpricetype,
  b.varietyid,
  v.opcode AS varietyopcode,
  v.varietyname,
  v.varietydescid,
  v.opcode AS varietydescopcode,
  v.varietydescno,
  v.varietydescname,
  b.accflag,
  b.defaultagtflag,
  b.storagecondition,
  b.transcondition,
  b.combinflag,
  b.customstax,
  b.minreqgoodsqty,
  b.financeno,
  b.otcflag,
  b.gmpflag,
  b.patentflag,
  b.securityflag,
  b.chineseflag,
  b.medicinetype,
  mt.ddlname AS medicinetypename,
  b.importflag,
  b.drugflag,
  b.poisonflag,
  b.biomedflag,
  b.bacterinflag,
  b.commonflag,
  b.medicineflag,
  b.credate,
  b.inputmanid,
  b.memo,
  b.usestatus,
  v.varietyno,
  b.busiscope,
  bs.scopename AS busiscopename,
  b.boxflag,
  b.integernx,
  b.function,
  b.familyplanflag,
  b.againchkflag,
  v.vardesclassname,
  v.vardesclassid,
  b.keyconserveflag,
  b.medicinesort,
  b.toinvdayswarn,
  b.limitedsaleflag,
  b.leastsaleqty,
  nvl(b.ephedrine, 0) AS ephedrine,
  b.iseggpeptide,
  b.gspflag,
  b.ecodeflag,
  b.constituent,
  b.reqprintquflag,
  b.highcostflag,
  b.lowcostflag,
  b.importsplitflag,
  b.armariumflag,
  b.implantable,
  b.externalagentia,
  b.artificialorganflag,
  b.interventional,
  b.gmpinvaliddate,
  b.productapproval,
  b.zx_finance_class,
  b.opcode || b.goodsname || b.currencyname || f.factoryname AS querycode,
  b.hiddenflag,
  b.groupmanagetype,
  b.grade,
  b.fzskcode,
  eg.materialcode,
  b.qxfirclass,
  b.qxsecclass,
  bs.zx_finance_class AS busi_zx_finance_class,
  bs.lbfl,
  bs.zx_finance_class_name AS busi_zx_finance_classname,
  bs.lbflname,
  fc.ddlname AS zx_finance_class_name,
  b.zx_cytj,
  f.brandintegration,
  gmt.ddlname AS groupmanagetypename,
  b.product_invaliddate,
  b.invaliddateflag,
  b.skcode,
  bs.splx,
  sc.ddlname AS storageconditionname,
  b.qxbusiclass,
  b.xgflag,
  nvl(b.dropingflag, 0) AS dropingflag,
  b.udicode,
  b.brandtype,
  b.relaname,
  b.zx_specgoods_flag,
  b.zx_tracecode_prefix,
  b.zx_ssbq,
  b.zx_gjypbwm,
  b.ruleid,
  b.zx_maingoodsid,
  b.zx_retainqty,
  b.zx_zyypgg,
  b.zx_mainflag,
  b.zx_policyno,
  b.zx_productdescr,
  b.zx_model,
  b.zx_productno,
  b.zx_productcode
FROM ranked_data a
JOIN ods_erp.pub_goods b ON a.goodsid=b.goodsid AND a.DW_CREATETIME=b.DW_CREATETIME
LEFT JOIN sqlmesh_dim.erp_pub_factory f ON b.factoryid = f.factoryid AND f.valid_to = DATE('9999-12-31')
LEFT JOIN sqlmesh_dim.erp_pub_goods_variety v ON b.varietyid = v.varietyid AND v.valid_to = DATE('9999-12-31')
LEFT JOIN sqlmesh_dim.erp_bms_busiscope_def bs ON b.busiscope = bs.scopedefid AND bs.valid_to = DATE('9999-12-31')
LEFT JOIN sqlmesh_dim.erp_pub_ddl_dtl mt ON b.medicinetype = mt.ddlid AND mt.sysid = 15 AND mt.valid_to = DATE('9999-12-31')
LEFT JOIN sqlmesh_dim.erp_pub_ddl_dtl fc ON b.zx_finance_class = fc.ddlid AND fc.sysid = 100021 AND fc.valid_to = DATE('9999-12-31')
LEFT JOIN sqlmesh_dim.erp_pub_ddl_dtl gmt ON b.groupmanagetype = gmt.ddlid AND gmt.sysid = 100104 AND gmt.valid_to = DATE('9999-12-31')
LEFT JOIN sqlmesh_dim.erp_pub_ddl_dtl sc ON b.storagecondition = sc.ddlid AND sc.sysid = 1 AND sc.valid_to = DATE('9999-12-31')
LEFT JOIN (
  SELECT t.goodsid, t.materialcode
  FROM ods_erp.pub_entry_goods t
  WHERE t.entryid = 64
  AND t.is_active = 1
) eg ON b.goodsid = eg.goodsid
WHERE b.goodsid > 0; 